name: Run Next.js Build and Tests

on:
  push:
    branches: [ "*" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x] # Specify the Node.js version
    name: Build and test on Node.js ${{ matrix.node }}
    defaults:
      working-directory: Frontend/frontend # Set the default working directory

    steps:
      - uses: actions/checkout@v4 # Checkout the repository
      
      - name: List files in Frontend directory
        run: ls -la # List files in the current working directory

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci # Install npm dependencies

      - name: Build the application
        run: npm run build --if-present # Build the application

      - name: Run tests
        run: npm run test # Adjust this to your test command if different
