name: Run Next.js Build and Tests

on:
  push:
    branches: [ "*" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x] # Specify the Node.js version
    name: Build and test on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4 # Checkout the repository
      
      - name: List files in Frontend directory
        run: ls -la Frontend/frontend # List files in the specific directory

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm' # Cache npm dependencies
          
      - name: Install dependencies
        run: npm ci
        working-directory: Frontend/frontend # Specify the correct directory

      - name: Build the application
        run: npm run build --if-present
        working-directory: Frontend/frontend # Specify the correct directory

      - name: Run tests
        run: npm run test # Adjust this to your test command if different
        working-directory: Frontend/frontend # Specify the correct directory
