name: Run Next.js Build and Tests

on:
  push:
    branches: [ "*" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x] # Specify the Node.js version
    name: Build and test on Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v4 # Checkout the repository
      
      - name: List files in Frontend directory
        run: ls -la Frontend/frontend # List files in the Frontend/frontend directory

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm' # Cache npm dependencies
          cache-dependency-path: Frontend/frontend/package-lock.json # Specify the path to package-lock.json

      - run: npm ci
        working-directory: Frontend/frontend # Install npm dependencies in the Frontend/frontend directory

      - run: npm run build --if-present
        working-directory: Frontend/frontend # Build the application

      - run: npm test
        working-directory: Frontend/frontend # Run tests
