name: Run Unit Tests

on:
  push:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21] 
    name: Run unit ests on Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@main
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Navigate to Backend directory
        run: cd Backend

      - name: Build the application
        run: mvn -f pom.xml clean package
        working-directory: Backend

      - name: Run tests
        run: mvn -f pom.xml test
        working-directory: Backend

